In [32]:
import glob, os, sys, shutil
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
import sklearn as skl
import xgboost


%load_ext autoreload
%autoreload 2
%matplotlib inline
if os.name == 'posix':
    %config InlineBackend.figure_format = 'retina' #retina display settings

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [8]:
from tpot import TPOTClassifier

In [18]:
df = pd.read_csv(filepath_or_buffer='./train.csv')
df_test = pd.read_csv(filepath_or_buffer='./test.csv')

XX = pd.concat([df.drop('Survived', axis = 1), df_test], axis = 0)
XX.drop('PassengerId', axis = 1, inplace=True)

XX['Nulls'] = XX.Cabin.isnull().astype('int') + XX.Age.isnull().astype('int')
XX['FamilySize'] = XX['SibSp'] + XX['Parch'] + 1

import re
def get_title(name):
    title_search = re.search(' ([A-Za-z]+)\.', name)
    # If the title exists, extract and return it.
    if title_search:
        return title_search.group(1)
    return ""

XX['Title'] = XX['Name'].apply(get_title)
XX['Title'] = XX['Title'].replace(['Lady', 'Countess','Capt', 'Col','Don', 
                                             'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona'], 'Rare')
XX['Title'] = XX['Title'].replace('Mlle', 'Miss')
XX['Title'] = XX['Title'].replace('Ms', 'Miss')
XX['Title'] = XX['Title'].replace('Mme', 'Mrs')
XX.drop(['Name'], inplace = True, axis = 1)

XX['Age'].fillna(XX.Age.median(), inplace = True)
XX['Age_bin'] = pd.cut(XX['Age'], bins=[0,12,20,40,120], labels=['Children','Teenage','Adult','Elder'])
XX.drop(['Age'], inplace = True, axis = 1)

XX['Cabin_mapped'] = XX['Cabin'].astype(str).str[0] # this captures the letter
# this transforms the letters into numbers
cabin_dict = {k:i for i, k in enumerate(XX.Cabin_mapped.unique())} 
XX.loc[:, 'Cabin_mapped'] = XX.loc[:, 'Cabin_mapped'].map(cabin_dict)
XX.drop(['Cabin'], inplace = True, axis = 1)


XX['Fare'].fillna(XX.Fare.median(), inplace = True)
XX['Fare_bin'] = pd.cut(XX['Fare'], bins=[0,7.91,14.45,31,120], labels=['Low_fare','median_fare','Average_fare','high_fare'])
XX.drop(['Fare'], inplace = True, axis = 1)

XX['Embarked'].fillna('S', inplace = True)

XX['Sex'] = XX['Sex'].map( {'female': 1, 'male': 0} ).astype(int)


XX.drop(['Ticket'], inplace = True, axis = 1)
XX.drop(['Parch'], inplace = True, axis = 1)
XX.drop(['SibSp'], inplace = True, axis = 1)

X_dummies = pd.get_dummies(XX, columns = ['Title', 'Sex', 'Nulls','Pclass', 'FamilySize',
                                          'Cabin_mapped', 'Embarked','Fare_bin', 'Age_bin'], drop_first= True)



X_dummies.head()

,Title_Miss,Title_Mr,Title_Mrs,Title_Rare,Sex_1,Nulls_1,Nulls_2,Pclass_2,Pclass_3,FamilySize_2,...,Cabin_mapped_7,Cabin_mapped_8,Embarked_Q,Embarked_S,Fare_bin_median_fare,Fare_bin_Average_fare,Fare_bin_high_fare,Age_bin_Teenage,Age_bin_Adult,Age_bin_Elder
0,0,1,0,0,0,1,0,0,1,1,...,0,0,0,1,0,0,0,0,1,0
1,0,0,1,0,1,0,0,0,0,1,...,0,0,0,0,0,0,1,0,1,0
2,1,0,0,0,1,1,0,0,1,0,...,0,0,0,1,1,0,0,0,1,0
3,0,0,1,0,1,0,0,0,0,1,...,0,0,0,1,0,0,1,0,1,0
4,0,1,0,0,0,1,0,0,1,0,...,0,0,0,1,1,0,0,0,1,0

In [41]:
X = X_dummies[:len(df)];
new_X = X_dummies[len(df):]
y = df.Survived

In [34]:
# X_train, X_test, y_train, y_test = skl.model_selection.train_test_split(X, y, test_size=0.33, random_state=42)

In [42]:
tpot = TPOTClassifier(verbosity=2, max_time_mins=25, max_eval_time_mins=0.04, population_size=40)
tpot.fit(X, y)

HBox(children=(IntProgress(value=0, description='Optimization Progress', max=40, style=ProgressStyle(descriptiâ€¦

Generation 1 - Current best internal CV score: 0.8294754887514554
Generation 2 - Current best internal CV score: 0.8294754887514554
Generation 3 - Current best internal CV score: 0.8339320665000584
Generation 4 - Current best internal CV score: 0.8339320665000584
Generation 5 - Current best internal CV score: 0.8339320665000584
Generation 6 - Current best internal CV score: 0.8339320665000584
Generation 7 - Current best internal CV score: 0.8339320665000584
Generation 8 - Current best internal CV score: 0.8339320665000584
Generation 9 - Current best internal CV score: 0.8339320665000584
Generation 10 - Current best internal CV score: 0.8339320665000584
Generation 11 - Current best internal CV score: 0.8339573166341996
Generation 12 - Current best internal CV score: 0.8350684289274332
Generation 13 - Current best internal CV score: 0.8350684289274332
Generation 14 - Current best internal CV score: 0.8350684289274332
Generation 15 - Current best internal CV score: 0.8350684289274332
Generation 16 - Current best internal CV score: 0.8350684289274332
Generation 17 - Current best internal CV score: 0.8350684289274332
Generation 18 - Current best internal CV score: 0.844057192972377
Generation 19 - Current best internal CV score: 0.844057192972377
Generation 20 - Current best internal CV score: 0.844057192972377
Generation 21 - Current best internal CV score: 0.844057192972377
Generation 22 - Current best internal CV score: 0.844057192972377
Generation 23 - Current best internal CV score: 0.844057192972377
Generation 24 - Current best internal CV score: 0.844057192972377
Generation 25 - Current best internal CV score: 0.844057192972377
Generation 26 - Current best internal CV score: 0.844057192972377
Generation 27 - Current best internal CV score: 0.844057192972377
Generation 28 - Current best internal CV score: 0.844057192972377
Generation 29 - Current best internal CV score: 0.844057192972377
Generation 30 - Current best internal CV score: 0.844057192972377
Generation 31 - Current best internal CV score: 0.844057192972377
Generation 32 - Current best internal CV score: 0.844057192972377
Generation 33 - Current best internal CV score: 0.844057192972377
Generation 34 - Current best internal CV score: 0.844057192972377
Generation 35 - Current best internal CV score: 0.844057192972377
Generation 36 - Current best internal CV score: 0.844057192972377
Generation 37 - Current best internal CV score: 0.844057192972377
Generation 38 - Current best internal CV score: 0.844057192972377
Generation 39 - Current best internal CV score: 0.844057192972377
Generation 40 - Current best internal CV score: 0.844057192972377
Generation 41 - Current best internal CV score: 0.844057192972377
Generation 42 - Current best internal CV score: 0.844057192972377
Generation 43 - Current best internal CV score: 0.844057192972377
Generation 44 - Current best internal CV score: 0.844057192972377
Generation 45 - Current best internal CV score: 0.844057192972377
Generation 46 - Current best internal CV score: 0.844057192972377
Generation 47 - Current best internal CV score: 0.844057192972377
Generation 48 - Current best internal CV score: 0.844057192972377
Generation 49 - Current best internal CV score: 0.844057192972377
Generation 50 - Current best internal CV score: 0.844057192972377
Generation 51 - Current best internal CV score: 0.844057192972377

25.001307533333332 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.
WARNING: TPOT may not provide a good pipeline if TPOT is stopped/interrupted in a early generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: GradientBoostingClassifier(Binarizer(GradientBoostingClassifier(input_matrix, learning_rate=0.5, max_depth=6, max_features=0.5, min_samples_leaf=3, min_samples_split=20, n_estimators=100, subsample=0.3), threshold=0.45), learning_rate=0.1, max_depth=5, max_features=0.2, min_samples_leaf=12, min_samples_split=10, n_estimators=100, subsample=0.6500000000000001)

TPOTClassifier(config_dict=None, crossover_rate=0.1, cv=5,
        disable_update_check=False, early_stop=None, generations=1000000,
        max_eval_time_mins=0.04, max_time_mins=25, memory=None,
        mutation_rate=0.9, n_jobs=1, offspring_size=None,
        periodic_checkpoint_folder=None, population_size=40,
        random_state=None, scoring=None, subsample=1.0, template=None,
        use_dask=False, verbosity=2, warm_start=False)

In [43]:
y_predict = tpot.predict(X_test)

In [44]:
(y_predict==y_test).mean()

0.8677966101694915

In [40]:
# tpot.export('tpot_pipeline.py')

In [45]:
y_tpot_prediction = tpot.predict(new_X)
submission = pd.concat([df_test.PassengerId, pd.DataFrame(y_tpot_prediction)], axis = 'columns')
submission.columns = ["PassengerId", "Survived"]
submission.to_csv('tpot_01.csv', header=True, index = False)